/*
 * @description: 人脸识别管理
 * @author: songliubiao
 * @lastEditors: songliubiao
 * @Date: 2020-07-03 14:37:48
 * @LastEditTime: 2020-07-22 19:24:52
 */ 

declare const APIS: [
  'API_FACEIDENTIFY_INDEX_LIST',
  'API_FACEIDENTIFY_INDEX_USERLIST',
  'API_FACEIDENTIFY_INDEX_PASSAGELIST',
  'API_FACEIDENTIFY_INDEX_ADD',
  'API_FACEIDENTIFY_INDEX_EDIT',
  'API_FACEIDENTIFY_INDEX_DEL',
  'API_FACEIDENTIFY_INDEX_SHUTTLELIST',
  'API_FACEIDENTIFY_INDEX_CUSTOM',
  'API_FACEIDENTIFY_INDEX_GLOBALCUSTOM'
]

type API_FACEIDENTIFY_INDEX = {
  [api in (typeof APIS)[number]]: string
}

export interface API_FACEIDENTIFY_INDEX {
  API_FACEIDENTIFY_INDEX
}
